apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: spring-boot-k8s
spec:
  selector:
    matchLabels:
      app: spring-boot-k8s
  replicas: 3 # Number of replicas that will be created for this deployment
  minReadySeconds: 120
  strategy:
    type: RollingUpdate # RollingUpdate, which means new versions are rolled out gradually to pods to avoid downtime.
  template:
    metadata:
      labels:
        app: spring-boot-k8s
    spec:
      containers:
        - name: spring-boot-k8s
          image: juanjoaquino05/alten-hotel-api:latest # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8085 # The port that the container is running on in the cluster
          livenessProbe:
            httpGet:
              path: /
              port: 8085
            initialDelaySeconds: 120
            periodSeconds: 120
          envFrom:
            - configMapRef:
                name: app-config